"""Generate the technical conversion LUT: Apple Log / BT.2020 -> Rec.709.

This is the CST node. It does one job and no creative grading, so the look LUT
downstream stays interchangeable.

    apple log code -> scene linear (BT.2020) -> gamut matrix -> tone map -> encode
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
import colorlib as C


def apple_log_to_dwg(code):
    """CST IN: Apple Log / BT.2020 -> DaVinci Intermediate / DaVinci Wide Gamut.

    Log to log, wide gamut to wider gamut. Nothing is tone mapped and nothing
    clips, so the primaries stage that runs after this has full headroom.
    """
    scene = C.apple_log_to_scene_linear(code)
    dwg = C.apply_matrix(scene, C.BT2020_TO_DWG)
    return np.clip(C.dwg_encode(np.clip(dwg, 0.0, None)), 0.0, 1.0)


def dwg_to_rec709(code, tonemap="aces", encode="rec709a"):
    """CST OUT: DaVinci Wide Gamut -> Rec.709, applying the tone map."""
    scene = np.clip(C.dwg_decode(code), 0.0, None)
    if tonemap == "aces":
        ap1 = C.apply_matrix(scene, C.DWG_TO_AP1)
        tone = C.tonemap_aces(np.clip(ap1, 0.0, None))
        lin709 = C.apply_matrix(tone, C.AP1_TO_REC709)
    else:
        lin709 = C.apply_matrix(scene, C.DWG_TO_REC709)
        lin709 = C.TONEMAPS[tonemap](np.clip(lin709, 0.0, None))
    return C.ENCODERS[encode](np.clip(lin709, 0.0, 1.0))


def apple_log_to_rec709(code, tonemap="aces", encode="gamma24", exposure=0.0):
    scene = C.apple_log_to_scene_linear(code)
    if exposure:
        scene = scene * (2.0 ** exposure)

    if tonemap == "aces":
        # The ACES fit is defined in AP1, so detour through that gamut.
        display = C.AP1_TO_REC709 @ np.eye(3)
        ap1 = C.apply_matrix(scene, C.BT2020_TO_AP1)
        tone = C.tonemap_aces(np.clip(ap1, 0.0, None))
        lin709 = C.apply_matrix(tone, C.AP1_TO_REC709)
    else:
        lin709 = C.apply_matrix(scene, C.BT2020_TO_REC709)
        lin709 = C.TONEMAPS[tonemap](np.clip(lin709, 0.0, None))

    return C.ENCODERS[encode](np.clip(lin709, 0.0, 1.0))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=65)
    ap.add_argument("--tonemap", default="aces", choices=list(C.TONEMAPS))
    ap.add_argument("--encode", default="gamma24", choices=list(C.ENCODERS))
    ap.add_argument("--exposure", type=float, default=0.0)
    ap.add_argument("--stage", default="direct", choices=["direct", "in", "out"],
                    help="direct = one LUT to Rec.709; in/out = the DWG pair")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    grid = C.identity_grid(args.size)
    if args.stage == "in":
        out = apple_log_to_dwg(grid)
        title = "AppleLog_BT2020_to_DaVinciWideGamut"
        notes = ["In:  Apple Log, BT.2020 primaries, FULL range",
                 "Out: DaVinci Intermediate, DaVinci Wide Gamut",
                 "No tone map. This is the CST IN of the working-space pair."]
    elif args.stage == "out":
        out = dwg_to_rec709(grid, args.tonemap, args.encode)
        title = f"DaVinciWideGamut_to_Rec709_{args.tonemap}"
        notes = ["In:  DaVinci Intermediate, DaVinci Wide Gamut",
                 f"Out: Rec.709 primaries, {args.encode} transfer",
                 f"Tone map: {args.tonemap}"]
    else:
        out = apple_log_to_rec709(grid, args.tonemap, args.encode, args.exposure)
        title = f"AppleLog_BT2020_to_Rec709_{args.tonemap}"
        notes = ["In:  Apple Log, BT.2020 primaries, FULL range",
                 f"Out: Rec.709 primaries, {args.encode} transfer",
                 f"Tone map: {args.tonemap}   Exposure: {args.exposure:+.2f} stops"]

    C.write_cube(args.out, out, args.size, title,
                 comments=["Generated by content/grade/tools/make_cst.py"] + notes)

    # Sanity anchors. An 18% grey card must land near 0.39 or the CST is wrong.
    from colour.models import log_encoding_AppleLogProfile as enc
    print(f"wrote {args.out}  ({args.size}^3)")
    if args.stage != "direct":
        return
    print("  anchor checks (Rec.709 output code):")
    for name, lin in [("18% grey", 0.18), ("90% white", 0.90),
                      ("2 stops over grey", 0.72), ("4 stops over", 2.88),
                      ("deep shadow 1%", 0.01)]:
        cv = np.array([[enc(lin)] * 3])
        res = apple_log_to_rec709(cv, args.tonemap, args.encode, args.exposure)
        print(f"    {name:20} log {cv[0][0]:.4f} -> {res[0][0]:.4f}")


if __name__ == "__main__":
    main()
